---
language: python
python:
  - '2.7'
services: docker

env:
  global:
    - ROLE_NAME=git
    - ANSIBLE_VERSION=">=2.7.0"
  matrix:
    - MOLECULE_IMAGE=centos:7
      MOLECULE_IMAGE_NAME=centos7
    - MOLECULE_IMAGE=fedora:29
      MOLECULE_IMAGE_NAME=fedora29
    - MOLECULE_IMAGE=ubuntu:bionic
      MOLECULE_IMAGE_NAME=ubuntu-bionic

install:
  - pip install testinfra==1.19.0 molecule==2.20.0
  - pip install --upgrade docker ansible$ANSIBLE_VERSION

before_script:
  # Rename repository name to the galaxy role name.
  - cd ../
  - mv ansible-role-$ROLE_NAME siavashoutadi.$ROLE_NAME
  - cd siavashoutadi.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
