---
- name: Install packages
  package:
    name: "{{ git_packages }}"
    state: present

- name: Apply global git configuration
  become: true
  become_user: "{{ git_user | default('root') }}"
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: "global"
  with_items: "{{ git_config }}"
  when: item.scope | default("global") == "global"

- name: Apply system git configuration
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: "system"
  with_items: "{{ git_config }}"
  when: item.scope | default("global") == "system"
